### ISSUE TITLE
Bug in PDK

### ISSUE THREAD

**Issue by jaspreetj** [lukasc-ubc/SiEPIC_EBeam_PDK#117]
PDK and KLayout is installed properly but some of the scripts are not working properly.

When I tried to convert path to waveguide, I get the following error:
![err](https://cloud.githubusercontent.com/assets/15523357/15054291/39d3380a-1324-11e6-948a-6c7c5330a436.png)

Even when I used the previous code, it failed to recognize the selection.
 
The following line returns false for all drawn paths: 
`o.shape.is_path()`
where o refers to object_selection.

If I copy paste a waveguide from a layout, the script works but does not work on newly created paths.
Some of the students in the edX course also encountered this error.

**Comment by jaspreetj** [comment]
problem still persists.
![error_occured_again](https://cloud.githubusercontent.com/assets/15523357/15067753/4ac3e940-1390-11e6-84d5-939698afd749.png)

**Comment by jaspreetj** [comment]
That fixed the issue with the script.
Also, it is must to keep the highlighted option to **Add**. Otherwise the created paths will not be considered as paths and the scripts will generate errors.
![untitled](https://cloud.githubusercontent.com/assets/15523357/15071019/318643f4-13a6-11e6-86b1-6922ba127006.png)

**Comment by lukasc-ubc** [comment]
strange, I don’t see this problem.
