### ISSUE TITLE
Netlist regeneration-- Parameter accuracy

### ISSUE THREAD

**Issue by luzeqin** [lukasc-ubc/SiEPIC_EBeam_PDK#124]
Netlist generation function has a limited digit for parameter accuracy. For example, for a ring with 5.05 um radius, the radius listed in the spi file is 5 um.

ebeam_dc_halfring_straight_te1550_6  N$13 N$14 N$15 N$16 ebeam_dc_halfring_straight_te1550 library="Design kits/ebeam_v1.2" wg_width=0.500u gap=0.100u **radius=5.000u** lay_x=65.05E-6 lay_y=60.97E-6 sch_x=3.2525E0 sch_y=3.0485E0

**Comment by lukasc-ubc** [comment]
fixed.
