### ISSUE TITLE
BUG: Waveguide Resize Function

### ISSUE THREAD

**Issue by jaspreetj** [lukasc-ubc/SiEPIC_EBeam_PDK#130]
If you make a duplicate of a waveguide and try to resize it, the original waveguide disappears after the operation.

Workaround: Always make a subtle change to the duplicated waveguide and then use the resize function.

**Comment by lukasc-ubc** [comment]
Hi Jaspreet,

Another related bug is reported on the edx course:

![image](https://user-images.githubusercontent.com/15843200/28510020-b2cec5c4-6ffa-11e7-9936-d17df24200d6.png)

**Comment by jaspreetj** [comment]
fixed the issue. check pull request.
