### ISSUE TITLE
KLayout Toolbar icon for INTERCONNECT

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC_EBeam_PDK#14]

**Comment by jaspreetj** [comment]
Finished. Check Pull Request.

**Comment by lukasc-ubc** [comment]
It should launch the simulation, i.e., the same as menu SiEPIC | Simulation.

Perhaps can you add "Circuit Simulation" under the icon?  Matching the other icons that have text.

**Comment by jaspreetj** [comment]
working on it.
