### ISSUE TITLE
Spiral Pcell not working well

### ISSUE THREAD

**Issue by rounaksingh** [lukasc-ubc/SiEPIC_EBeam_PDK#142]
Professor,
I tried to make spirals for 400um and 380um for test purpose. I found that the spiral Pcell is generating same spiral for total waveguide length 400um and 380um. Also, the length label shows 578um which I donot understand. I guess there is some problem with spirals generating algorithm

In picture, Spirals are being overlap to show that they are same.
![spiral_380um_over_400um](https://cloud.githubusercontent.com/assets/2233968/23678305/99f04a34-0351-11e7-9240-e412f5f2e81d.png)

![spiral_parameters](https://cloud.githubusercontent.com/assets/2233968/23678306/9b3aae52-0351-11e7-8b5b-6c5826f4d1b2.png)

**Comment by lukasc-ubc** [comment]
Hello Rounak,

The code is limited to making a spiral that starts at theta=0, and ends at theta=180.  It finds the closest number to what you ask for.  This is what the 578 µm is -- the actual length.

For my application, I didn't need to specify the length accurately, but I did want to know the length that was fabricated.

To get a spiral exactly the length you want, you need to make adjustments to the parameters.  For a desired length of 400 µm, I adjusted the radius and found that for R=5.84718 µm, you get 400.003 µm length.  One could write a Newton search algorithm to loop through the code to find the solution.    Or, there could be an exact analytic solution, but that would require an equation describing the length of the spiral, and as far as I know there is no analytic solution for the length of an Archimedes spiral.

regards
Lukas
