### ISSUE TITLE
Remove old MC macro codes

### ISSUE THREAD

**Issue by luzeqin** [lukasc-ubc/SiEPIC_EBeam_PDK#144]
Could you please delete "INTERCONNECT - WithinWafer MC simulation.lym" & "INTERCONNECT - WaferToWafer MC simulation.lym"? They were old version MC simulation codes, and have been abandoned for a year.

The MC code that is being used is "INTERCONNECT - MC simulation.lym", which configures both wafer to wafer and within wafer analysis.

**Comment by lukasc-ubc** [comment]
done. thanks.
