### ISSUE TITLE
Specify WG length

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC_EBeam_PDK#15]
Once drawn, give user ability to type in a length, and have waveguide adjust itself.

Add Length as parameter in waveguide PCell.  Gettable & Settable.

**Comment by jaspreetj** [comment]
Works but needs improvement. There are some bugs eg. sometimes the layout disappears upon the completion of the resizing operation.

press Ctrl + Shift + R to run the script while having a transient selection.

**Comment by lukasc-ubc** [comment]
Hi Jaspreet,

A few problems:

 - Layout disappears.  I've seen this before when using a GUI and performing operations.  In my case, the solution was to close the GUI first, then perform layout modifications

 - if you select the waveguide, it crashes.  only works if you select the path.  should work for both.  see my script "Waveguide_to_path"

 - remove 1st and last segments; these presumably never will be useful.

 - perhaps only list eligible segments: name those whose neighbour segments point in the same direction (middle of a U-shape being the only allowable one).

**Comment by lukasc-ubc** [comment]
fixed:

 - layout disappears

 - selection for PCell vs. GUIDING_PATH; both work

 - correctly measuring the path length including bends

 - added Undo functionality

 - removed 1st/last points.

to do:

 - quality control checking

 - perhaps only list eligible segments: name those whose neighbour segments point in the same direction (middle of a U-shape being the only allowable one).

**Comment by lukasc-ubc** [comment]
Bug:

 - if the segment to be moved is on the left, it applies the "diff" in the incorrect direction (makes the waveguide shorter instead of longer)

**Comment by jaspreetj** [comment]
working on the Bug and to do items.

**Comment by jaspreetj** [comment]
**Fixed: if the segment to be moved is on the left, it applies the "diff" in the incorrect direction (makes the waveguide shorter instead of longer)**

New Bug detected: Waveguide resizer does not work on a waveguide which has already been resized.

**Comment by lukasc-ubc** [comment]
Bug: segment says "horizontal" but it is vertical.

**Comment by lukasc-ubc** [comment]
did some GUI improvements.

**Comment by jaspreetj** [comment]
The script was giving me syntax errors. So I did following fixes. 

I commented out the line no. 110.

and changed line no. 79 from
`if len(o_selection)<>1:`
 to
`if len(o_selection)< 1:`
