### ISSUE TITLE
Segfault on KLayout 0.25 on Linux

### ISSUE THREAD

**Issue by nsmith5** [lukasc-ubc/SiEPIC_EBeam_PDK#156]
Not sure if this is a KLayout or Linux thing but `SiEPIC` is giving a segfault and klayout refuses to start on the latest development version. I'll post a screenshot shortly.

**Comment by nsmith5** [comment]
![siepic-crash](https://user-images.githubusercontent.com/12156185/28224119-bd87826e-6882-11e7-9e7e-98b2b03c06a6.png)

**Comment by nsmith5** [comment]
To reproduce: 
 - Build Klayout from source
 - Download SiEPIC compressed archive
 - Copy SiEPIC dot files into `~/.klayout`
 - Run `klayout`

**Comment by lukasc-ubc** [comment]
I've never built klayout myself. Can you try the compiled version on their page?
Are you using the latest siepic library? Or a release version?


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by nsmith5** [comment]
Same on both versions unfortunately. No compiled version for Fedora 26 and the Centos version requires older versions of ruby than my system is capable of supplying.

**Comment by lukasc-ubc** [comment]
Hi again,

Does it segfault when you start klayout by itself (without SiEPIC)?  Can you narrow it down to a particular script that causes it to crash?

**Comment by bpoulse** [comment]
This looks like it could possibly be a problem with the QT Binding module built for Ruby.

When you built klayout, did you use this option?
build.sh -with-qtbinding ...

Reference:
http://www.klayout.de/doc/programming/qt_binding.html
