### ISSUE TITLE
Problem using shift+O in klayout

### ISSUE THREAD

**Issue by cmekhiel** [lukasc-ubc/SiEPIC_EBeam_PDK#158]
I get an error when I try to snap to objects together in klayout. 
<img width="353" alt="15009655036653687" src="https://user-images.githubusercontent.com/8647702/28648704-852319c8-7224-11e7-9e81-84535a45906e.png">

[EBeam_cmekhiel2.zip](https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/files/1178343/EBeam_cmekhiel2.zip)

Thank you

**Comment by jaspreetj** [comment]
Seems like you are trying to snap two components after flattening the layout. You can only snap objects when they are not flattened. This is why you are getting the error.

**Comment by cmekhiel** [comment]
Hi, I have tried it without flattening and I still get the error.

**Comment by lukasc-ubc** [comment]
can you please upload the non-flattened layout so we can debug?

**Comment by lukasc-ubc** [comment]
i just improved the snapping code to provide more error messages when the object isn't an instance. namely can't align flattened polygons/shapes.

**Comment by cmekhiel** [comment]
I also have this issue with a new layout trying to snap 2 waveguides where nothing is flattened.

**Comment by cmekhiel** [comment]
It looks like I have this issue when I try to snap a path instance to an object from the library. I am able to snap 2 objects together-a directional coupler and a y branch . But I can't use shift+O to snap a path to the Y-branch. Should I always be using the path to waveguide function instead?

**Comment by lukasc-ubc** [comment]
we don't have a function to snap two waveguides to each other, unfortunately.  I can think of a way to do that; it would probably take 2 hours of coding to add a snap and merge waveguide feature.

path to object snapping: also doesn't work. use path to waveguide which does what you need.

**Comment by lukasc-ubc** [comment]
some feedback on your layout:

https://courses.edx.org/courses/course-v1:UBCx+Phot1x+2T2017/discussion/forum/b77035e9087eb9f3b8c43d8ec5abba3f59067576/threads/5980dd82a358c60a5d000235 <https://courses.edx.org/courses/course-v1:UBCx+Phot1x+2T2017/discussion/forum/b77035e9087eb9f3b8c43d8ec5abba3f59067576/threads/5980dd82a358c60a5d000235>
