### ISSUE TITLE
Klayout. attempt to connect waveguides

### ISSUE THREAD

**Issue by Mohammadahmadi** [lukasc-ubc/SiEPIC_EBeam_PDK#167]
wave guides are disconnected and i tried to connect them to each other by klayout instructions like: shift+O or changing the WG to path and vice versa. but i was not successful! does my Klayout have a problem?? thanks

**Comment by lukasc-ubc** [comment]
implemented in SiEPIC-Tools and EBeam PDK v0.3.0
