### ISSUE TITLE
cleanup for v0.3.0 EBeam and GSiP PDKs

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC_EBeam_PDK#170]
Hi Mustafa, Jaspreet,

Can you please help as follows?

for GSiP, EBeam, and EBeam-dev, update:

 - refer to ebeam_dc_halfring_arc in EBeam-dev, and ebeam_dc_halfring_straight in EBeam as examples
 - arc waveguides for bends: use arc_wg or arc_wg_xy, from SiEPIC.utils
  - replace all layout_arc_wg_dbu with the above
 - from SiEPIC._globals import PIN_LENGTH, for the length of the pin, instead of hard coded
 - ensure all pins are pointing out of the device (order of vertices)
 - update all layers to use TECHNOLOGY global variable

check all components, including waveguide snapping.

**Comment by mustafacc** [comment]
Can you take a look this [IME PDK PCell](https://github.com/lukasc-ubc/SiEPIC_IME/commit/df8d2564ee582d81e305049b6d9ebde425dc72c6)? If it's good then I'll proceed with modifying the EBeam pcells on that framework (with ebeam tech.)

Thanks.

**Comment by lukasc-ubc** [comment]
Awesome, thanks.  Did some fixes.
