### ISSUE TITLE
KLayout integration doesn't fully work for KLayout version 0.25

### ISSUE THREAD

**Issue by GuanhuiWang** [lukasc-ubc/SiEPIC_EBeam_PDK#174]
The integration lacks some buttons for KLayout version 0.25 such as the "configure shortcut key" button.
<img width="986" alt="screen shot 2018-01-08 at 3 57 54 pm" src="https://user-images.githubusercontent.com/22895092/34698395-c7d161e0-f48c-11e7-8dbd-0c2080a539ce.png">

**Comment by lukasc-ubc** [comment]
Thanks Guanhui,

It also looks like you are running an older version of the PDK.  

Can you please upgrade?  Delete the old one, and install the new one using Tools | Package Manager, by selecting EBeam PDK.

The initialization is automatically run on start-up. Can you please check if the hotkeys work?  

e.g., w, v, i, ...

thank you

**Comment by jflueckiger** [comment]
Lukas, 
the shortcuts work for me with the latest (pulled 5mins ago). 
J

**Comment by GuanhuiWang** [comment]
Thanks Lukas. I am using CentOS 7. Might did something wrong, but when I removed all the old files and recopied the new ones, all the integration buttons were gone. It is very possible that I messed it up, will do some more tests tomorrow.

What I did to get the above picture in the first place was just updated KLayout. The config shortcut key button was there for KLayout v 0.24. 
![screen shot 2018-01-10 at 5 30 50 pm](https://user-images.githubusercontent.com/22895092/34804172-08f14ae6-f62c-11e7-8445-6d49fb4dffeb.png)

**Comment by lukasc-ubc** [comment]
Hi again,

Could you please try installing it using the Package Manager, rather than copying files manually?  Also please check File | Log view and let me know what you see there (screenshot can be pasted here).

Instructions:
https://github.com/lukasc-ubc/SiEPIC-Tools/wiki/Installation

**Comment by mustafacc** [comment]
I'm seeing the following errors when installing the package on my Linux (Ubuntu 16.04.3)
![capture](https://user-images.githubusercontent.com/8067688/34838553-590aae00-f6b3-11e7-8203-0459dc54f70c.PNG)

And this is the result on my Windows 10 machine
![capture](https://user-images.githubusercontent.com/8067688/34838852-7576c528-f6b4-11e7-8435-614d5dd4e336.PNG)

**Comment by JeffSteidle** [comment]
Hi Mustafa,

I ran into the same errors on my Windows 10 machine earlier in the week. After digging through the files I found that the cause was the version of Lumerical Interconnect that was installed. The errors went away after I updated Interconnect.

-Jeff

**Comment by mustafacc** [comment]
Thanks, Jeff, I see that updating Interconnect to 7.5 has resolved my issue.

**Comment by lukasc-ubc** [comment]
Wow, thank you both for figuring this out.

**Comment by lukasc-ubc** [comment]
Hi Mustafa,

To address the Linux system problem:

I released SiEPIC-Tools v0.3.8.  Please update to that one.  Then remove the Windows_Python_Packages, which seems to be causing an issue where it conflicts with the Linux install of numpy/multiarray.

Let me know if that works!
Lukas

**Comment by lukasc-ubc** [comment]
You still need numpy. It can be installed either via the Windows package, or some other means. 
I removed the dependency since there is no mechanism to only make it for Windows. OS X and Linux doesn’t need it and it was causing problems for Linux. 


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by GuanhuiWang** [comment]
Hi Lukas,

Sorry for the late reply, finally got around to this. I tested it on a clean VM (CentOS 7), the installation basically went through but with some "Stream has unknown format" error. Then after installation, the integration buttons are there still without the "config shortcut key" button. Attached files are installation error, Layout after installation and log viewer, respectively. 
![screen shot 2018-01-16 at 2 27 49 pm](https://user-images.githubusercontent.com/22895092/35015755-a50e59ee-faca-11e7-962e-d25049a6d5a8.png)
![screen shot 2018-01-16 at 2 28 07 pm](https://user-images.githubusercontent.com/22895092/35015756-a51f70ee-faca-11e7-8a6a-1fbce686ab24.png)
![screen shot 2018-01-16 at 2 35 45 pm](https://user-images.githubusercontent.com/22895092/35015757-a5309d2e-faca-11e7-8fa3-7a5d65a26844.png)

**Comment by lukasc-ubc** [comment]
All that looks ok and as expected. 


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by MohamedElRayany** [comment]
I followed the instructions and still I have some issues. I tried to explain them in this [thread](https://github.com/lukasc-ubc/SiEPIC-Tools/issues/62).
