### ISSUE TITLE
Changing pinRec layer

### ISSUE THREAD

**Issue by mustafacc** [lukasc-ubc/SiEPIC_EBeam_PDK#176]
Should we change/standardize pinRec layer on EBeam to match GSiP on SiEPIC-Tools? It would be nice to click and drop EBeam components on GSiP technology layout and have the whole layout be compatible and ready to go to INTC.

**Comment by lukasc-ubc** [comment]
Makes sense.  Also to be consistent with SiEPIC_IME_Library.  
Waveguide: 1/0
Waveguide Pin: 1/10

The nice thing is that doesn’t affect any of the fabrication, since these are just for internal use.

**Comment by mustafacc** [comment]
https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/commit/5b2b2d4ab604c79b994873793feb6563d47e3c5e

**Comment by lukasc-ubc** [comment]
We need to update all the GDS components in the library, the PCells, as well as all the examples. .. !
