### ISSUE TITLE
Invoking klayout in script mode

### ISSUE THREAD

**Issue by thomaslima** [lukasc-ubc/SiEPIC_EBeam_PDK#178]
Hi everyone,

In our lab, all our structures are coded in python. We invoke klayout in batch mode, with the option `-b`. But in the new version of the PDK, we started having a lot of issues because while importing SiEPIC from the repo siepic_tools, a lot of the files tried to start a GUI, resulting in the following error:
`Fatal: QWidget: Cannot create a QWidget without QApplication`

See for example `SiEPIC._globals`, which in turn calls `SiEPIC.core.WaveguideGUI()` unnecessarily.

I will try to isolate these GUI events, but It would be nice to avoid them in general imports. Maybe test files would help?

Thanks!

**Comment by lukasc-ubc** [comment]
Hi Thomas,
I have never worked with SiEPIC tools in batch mode.  All our layout scripts, in Python, are called using the IDE within KLayout (including creating very large 100 mm^2 designs in a script). Is there a reason to operate externally, rather than having the scripts run directly within KLayout?
Regarding that error, it is possible that it may disappear in the most recent version, as we are changing how the GUIs are created.

**Comment by thomaslima** [comment]
Dear Lukas,

Apart from the convenience, that means we can also launch these scripts from a server without GUI. I assumed you'd also find it convenient. Imagine having a Git server with continuous integration so that masks were compiled after every collaborative commit. Also the klayout IDE is not the best editor for python scripts. I can show you the environment that Alex Tait and I set up for this. We have some bandwidth do dedicate to that. We are considering collaborating to the project more directly in the near future.

Thomas

**Comment by lukasc-ubc** [comment]
Wow, Thomas.  That sounds very interesting.

Perhaps we could schedule a teleconference and discuss these ideas further. I’d love to see this.  Do you have a means of getting Git to call KLayout?  One place where I was thinking this would be useful is for automatically merging layouts (e.g., edX course, or as you say in collaborative research projects). For this, I don’t think I need SiEPIC-Tools….

**Comment by thomaslima** [comment]
Yes. Some time ago we decided to use our own git server in our lab (instead of GitHub) with a software called gitlab. That means we have control over everything installed in the machine, and continuous integration would be free. I think something like that with GitHub would be paid (look up Travis CI). I once set it to compile a latex document after each commit so I could send a download link to the up-to-date pdf to my advisor as we were working on it. I can assume the same can be done for this. To give you an example, one of my gds files had three different subcells generated by three different scripts and a fourth script that combined these cells and arrayed them into a wafer.

**Comment by lukasc-ubc** [comment]
Hi Thomas,

Have you had a chance to look at the original problem of disabling or moving the GUI initialization?

Also, did you build a version of KLayout with the newer Qt that doesn't have the problem reported https://github.com/klayoutmatthias/klayout/issues/20

**Comment by thomaslima** [comment]
Hi @lukasc-ubc I compiled klayout from source with Qt5.9.4 as they suggested. The newer version did not render the canvas correctly. I have no issues with disabled GUI. It rarely happens. I will try to compile it in such a way that python, ruby and Qt gets bundled together in the .app, so that I can just share the program with my labmates. I really want to use python3, not the default python2 they use.

I was not able to change the code in the PDK to avoid those yet. right now I am still using script mode, but allow the window to start. I compile my masks in my laptop for now. I will update you when I have a pull request to do.

**Comment by lukasc-ubc** [comment]
Hi Thomas,

Perhaps for Python3 you could choose to compile with a relatively standard installation, such as Anaconda.  Then the procedure for the user would be to install Anaconda first.  Maybe Matthias at KLayout will be ok with having two branches (default python2 and Anaconda Python 3).  Are you doing this on MacOS or Linux?

By the way, what is better about Python 3?  I have to support both presently… 

Qt5.9.4: are you saying that this works better than the other?  Perhaps you can add your build to KLayout’s GitHub.

**Comment by thomaslima** [comment]
I am using macOS! Python2 is thankfully soon to be dead. I only program in python3. The one that kazzz compiled has qt 5.9.3. I had a colleague download their version and our script failed. An error was thrown saying that the theme "cocoa" was not available or something.

My compiled version did not bundle the qt with the app, so I have to have qt somewhere. I want to fix that first, then move forward. If I get a stable .dmg, I will submit to their GitHub.
