### ISSUE TITLE
'points_to_path' replaced; taper_te1550 needs updating

### ISSUE THREAD

**Issue by StephenHLin** [lukasc-ubc/SiEPIC_EBeam_PDK#179]
The function called when drawing taper_te1550 still uses the legacy 'points_to_path' function that was removed. Currently drawing the taper shows an error:
`name 'points_to_path' is not defined`

**Comment by mustafacc** [comment]
fixed
https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/commit/b7be62e2016cc4a8db9bef0da266d2522cd8a51f
