### ISSUE TITLE
INTERCONNECT interoperability: growing tmp folder 

### ISSUE THREAD

**Issue by jfluecki** [lukasc-ubc/SiEPIC_EBeam_PDK#27]
.lsf and .spi files are saved in %KLAYOUT_HOME%/tmp. They should be deleted after INTERCONNECT gets closed.

**Comment by rounaksingh** [comment]
Hi,
I have added little code for deleting tmp files generated by macro. I have already verified the code in linux. Please verify the code in windows and mac.  Let me know if it works

**Comment by lukasc-ubc** [comment]
now using python tempfile module which does this automatically.
