### ISSUE TITLE
Spice export for INTERCONNECT, netlist trimming

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC_EBeam_PDK#56]
- check that there is only 1 laser.
- search the Netlist and remove components that are not connected to a laser/detector.  Performance improvement especially for MC simulation.

**Comment by lukasc-ubc** [comment]
Graph connected components:
 - https://breakingcode.wordpress.com/2013/04/08/finding-connected-components-in-a-graph/

**Comment by jaspreetj** [comment]
Do we just want a group of elements or they need to be in a particular order?

for eg. 
Group #1: a, b, c, d, e, f

Can it be like:
Group #1: c, b, a, d, f, e

**Comment by lukasc-ubc** [comment]
Order doesn't matter. They just need to end up in the (short) spice export.
The main purpose is to remove the components that aren't part of the
simulation in order to speed up the time consuming import in interconnect.

On Apr 23, 2016, at 12:02 AM, Jaspreet Jhoja <notifications@github.com>
wrote:

Do we just want a group of elements or they need to be in a particular
order?

for eg.
Group #1 <https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/issues/1>: a, b,
c, d, e, f

Can it be like:
Group #1 <https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/issues/1>: c, b,
a, d, f, e

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/issues/56#issuecomment-213678168>

**Comment by jaspreetj** [comment]
working on it. Almost finished it.

**Comment by lukasc-ubc** [comment]
Hi Jaspreet,

Thanks for your pull request!  There was a merge conflict, so I just downloaded your file and merged it myself.  Yes, please do add this to the MC Simulations.

Do we need the disconnected ports on the top of the device?  (I don't think so...)

**Comment by jaspreetj** [comment]
I just implemented this to the MC simulations and cleared the unused ports. 

Do we still need the **generate_short_Spice_file(topcell, optical_waveguides, optical_components)** function in the SiEPIC Functions?

If not, can I remove the function and add the newly created function to the Functions file?

**Comment by lukasc-ubc** [comment]
I think it is working well.

I have merged it into the main function, and removed the incomplete function you mentioned.

thank you!
Lukas
