### ISSUE TITLE
MC for Original GCs

### ISSUE THREAD

**Issue by jaspreetj** [lukasc-ubc/SiEPIC_EBeam_PDK#71]
Currently working on it.

**Comment by jaspreetj** [comment]
Completed it. Check the Pull Request.

**Comment by lukasc-ubc** [comment]
fixed nominal design was incorrect.

**Comment by jaspreetj** [comment]
"Namely, do you simply expand/shrink each Si box either in the width
(symmetric change) or height dimension?  Create a diagram for this"

Do you mean what I did in FDTD solutions?

**Comment by lukasc-ubc** [comment]
Yes, create a diagram illustrating the FDTD simulation, specifically which parameters were varied, so people know what you did.
