### ISSUE TITLE
MC Gui issues

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC_EBeam_PDK#74]
closed GUI, then tried to run it again:

![image](https://cloud.githubusercontent.com/assets/15843200/14413292/48bf8ae8-ff2a-11e5-8b83-3576ddf3bb8b.png)

**Comment by jaspreetj** [comment]
Opened a Layout and then MC GUI. Closed it and ran it again.
No errors occurred for me. 
Can you post a video?

**Comment by lukasc-ubc** [comment]
this might have been caused by the GUI from the waveguide resize?  I can’t reproduce after my fixes.
