### ISSUE TITLE
Waveguide Resize

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC_EBeam_PDK#86]
It shrinks the length rather than increases it...  Did the bug get re-introduced?  I know you fixed this before.

**Comment by jaspreetj** [comment]
Fixed it.

**Comment by lukasc-ubc** [comment]
It works for horizontal movements (vertical segment) but incorrect for the horizontal segments. 
Try your 12 MZI script and adjust those waveguides. 


Lukas Chrostowski
Associate Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by jaspreetj** [comment]
Fixed it. should work for both horizontal and vertical segments.
