### ISSUE TITLE
Warning if first/last waveguide segments are not Manhattan

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC_EBeam_PDK#99]
In Path-to-Waveguide, check if the first/last waveguide segments are Manhattan.  If not, issue a Warning, with a Cancel or OK button – similar operation as "One of the waveguide segments has insufficient length to accommodate the radius".

Without this warning, the snapping doesn't work, but there is no warming or feedback to the user that the waveguide isn't Manhattan.

![image](https://cloud.githubusercontent.com/assets/15843200/14776822/c4c8dc9e-0a7d-11e6-954c-e52617d9592e.png)

**Comment by jaspreetj** [comment]
Fixed it
